#ifndef SQL_CONNECTION_H
#define SQL_CONNECTION_H

#define SQL_CONNECTION_HOST		"172.31.24.95"
#define SQL_CONNECTION_USERNAME	"client"
#define SQL_CONNECTION_PASSWORD	"password"
#define SQL_CONNECTION_DB_NAME	"test"
#define SQL_CONNECTION_PORT		0
#define SQL_CONNECTION_SOCKET	NULL
#define SQL_CONNECTION_OPTIONS	0

#endif